$(function () {

    //$.getJSON('https://www.highcharts.com/samples/data/jsonp.php?filename=world-population-density.json&callback=?', function (data) {

var data = [{"name":"Afghanistan","value":55.3,"code":"AF"},
{"name":"Albania","value":95.1,"code":"AL"},
{"name":"Algeria","value":93.6,"code":"DZ"},
{"name":"Andorra","value":100,"code":"AD"},
{"name":"Angola","value":49,"code":"AO"},
{"name":"Antigua and Barbuda","value":97.9,"code":"AG"},
{"name":"Argentina","value":99.1,"code":"AR"},
{"name":"Armenia","value":100,"code":"AM"},
{"name":"Australia","value":100,"code":"AU"},
{"name":"Austria","value":100,"code":"AT"},
{"name":"Azerbaijan","value":87,"code":"AZ"},
{"name":"Bahamas","value":98.4,"code":"BS"},
{"name":"Bahrain","value":100,"code":"BH"},
{"name":"Bangladesh","value":86.9,"code":"BD"},
{"name":"Barbados","value":99.7,"code":"BB"},
{"name":"Belarus","value":99,"code":"BY"},
{"name":"Belgium","value":100,"code":"BE"},
{"name":"Belize","value":99.5,"code":"BZ"},
{"name":"Benin","value":77.9,"code":"BJ"},
{"name":"Bhutan","value":100,"code":"BT"},
{"name":"Bolivia (Plurinational State of)","value":90,"code":"BO"},
{"name":"Bosnia and Herzegovina","value":99.9,"code":"BA"},
{"name":"Botswana","value":96.2,"code":"BW"},
{"name":"Brazil","value":98.1,"code":"BR"},
{"name":"Brunei Darussalam","value":null,"code":"BN"},
{"name":"Bulgaria","value":99.4,"code":"BG"},
{"name":"Burkina Faso","value":82.3,"code":"BF"},
{"name":"Burundi","value":75.9,"code":"BI"},
{"name":"Cabo Verde","value":91.7,"code":"CV"},
{"name":"Cambodia","value":75.5,"code":"KH"},
{"name":"Cameroon","value":75.6,"code":"CM"},
{"name":"Canada","value":99.8,"code":"CA"},
{"name":"Central African Republic","value":68.5,"code":"CF"},
{"name":"Chad","value":50.8,"code":"TD"},
{"name":"Chile","value":99,"code":"CL"},
{"name":"China","value":95.5,"code":"CN"},
{"name":"Colombia","value":91.4,"code":"CC"},
{"name":"Comoros","value":90.1,"code":"CX"},
{"name":"Congo","value":76.5,"code":"CG"},
{"name":"Cook Islands","value":99.9,"code":"CK"},
{"name":"Costa Rica","value":97.8,"code":"CR"},
{"name":"Côte d'Ivoire","value":99.6,"code":"CI"},
{"name":"Croatia","value":94.9,"code":"HR"},
{"name":"Cuba","value":100,"code":"CU"},
{"name":"Cyprus","value":100,"code":"CY"},
{"name":"Czech Republic","value":81.9,"code":"CZ"},
{"name":"Democratic People's Republic of Korea","value":99.7,"code":"KP"},
{"name":"Democratic Republic of the Congo","value":52.4,"code":"CD"},
{"name":"Denmark","value":100,"code":"DK"},
{"name":"Djibouti","value":90,"code":"DJ"},
{"name":"Dominica","value":null,"code":"DM"},
{"name":"Dominican Republic","value":84.7,"code":"DO"},
{"name":"Ecuador","value":86.9,"code":"EC"},
{"name":"Egypt","value":99.4,"code":"EG"},
{"name":"El Salvador","value":93.8,"code":"SV"},
{"name":"Equatorial Guinea","value":47.9,"code":"GQ"},
{"name":"Eritrea","value":57.8,"code":"ER"},
{"name":"Estonia","value":99.6,"code":"EE"},
{"name":"Ethiopia","value":57.3,"code":"ET"},
{"name":"Fiji","value":95.7,"code":"FJ"},
{"name":"Finland","value":100,"code":"FI"},
{"name":"France","value":100,"code":"FR"},
{"name":"Gabon","value":93.2,"code":"GA"},
{"name":"Gambia","value":9032,"code":"GM"},
{"name":"Georgia","value":100,"code":"GE"},
{"name":"Germany","value":100,"code":"DE"},
{"name":"Ghana","value":88.7,"code":"GH"},
{"name":"Greece","value":100,"code":"GR"},
{"name":"Grenada","value":96.6,"code":"GD"},
{"name":"Guatemala","value":92.8,"code":"GT"},
{"name":"Guinea","value":76.8,"code":"GN"},
{"name":"Guinea-Bissau","value":79.3,"code":"GW"},
{"name":"Guyana","value":98.3,"code":"GY"},
{"name":"Haiti","value":57.7,"code":"HT"},
{"name":"Honduras","value":91.2,"code":"HN"},
{"name":"Hungary","value":100,"code":"HU"},
{"name":"Iceland","value":100,"code":"IS"},
{"name":"India","value":94.1,"code":"IN"},
{"name":"Indonesia","value":87.4,"code":"ID"},
{"name":"Iran (Islamic Republic of)","value":96.2,"code":"IR"},
{"name":"Iraq","value":86.6,"code":"IQ"},
{"name":"Ireland","value":97.9,"code":"IE"},
{"name":"Israel","value":100,"code":"IL"},
{"name":"Italy","value":100,"code":"IT"},
{"name":"Jamaica","value":93.8,"code":"JM"},
{"name":"Japan","value":100,"code":"JP"},
{"name":"Jordan","value":96.9,"code":"JO"},
{"name":"Kazakhstan","value":92.9,"code":"KZ"},
{"name":"Kenya","value":63.2,"code":"KE"},
{"name":"Kiribati","value":66.9,"code":"KI"},
{"name":"Kuwait","value":99,"code":"KW"},
{"name":"Kyrgyzstan","value":90,"code":"KG"},
{"name":"Lao People's Democratic Republic","value":75.7,"code":"LA"},
{"name":"Latvia","value":99.3,"code":"LV"},
{"name":"Lebanon","value":99,"code":"LB"},
{"name":"Lesotho","value":81.8,"code":"LS"},
{"name":"Liberia","value":75.6,"code":"LR"},
{"name":"Libya","value":null,"code":"LY"},
{"name":"Lithuania","value":96.6,"code":"LT"},
{"name":"Luxembourg","value":100,"code":"LU"},
{"name":"Madagascar","value":51.5,"code":"MG"},
{"name":"Malawi","value":90.2,"code":"MW"},
{"name":"Malaysia","value":98.2,"code":"MY"},
{"name":"Maldives","value":98.6,"code":"MV"},
{"name":"Mali","value":77,"code":"ML"},
{"name":"Malta","value":100,"code":"MT"},
{"name":"Marshall Islands","value":94.6,"code":"MH"},
{"name":"Mauritania","value":57.9,"code":"MR"},
{"name":"Mauritius","value":99.9,"code":"MU"},
{"name":"Mexico","value":96.1,"code":"MX"},
{"name":"Micronesia (Federated States of)","value":89,"code":"FM"},
{"name":"Monaco","value":100,"code":"MC"},
{"name":"Mongolia","value":64.4,"code":"MN"},
{"name":"Montenegro","value":99.7,"code":"ME"},
{"name":"Morocco","value":85.4,"code":"MA"},
{"name":"Mozambique","value":51.1,"code":"MZ"},
{"name":"Myanmar","value":80.6,"code":"MM"},
{"name":"Namibia","value":91,"code":"NA"},
{"name":"Nauru","value":96.5,"code":"NR"},
{"name":"Nepal","value":91.6,"code":"NP"},
{"name":"Netherlands","value":100,"code":"NL"},
{"name":"New Zealand","value":100,"code":"NZ"},
{"name":"Nicaragua","value":87,"code":"NI"},
{"name":"Niger","value":58.2,"code":"NE"},
{"name":"Nigeria","value":68.5,"code":"NG"},
{"name":"Niue","value":98.5,"code":"NU"},
{"name":"Norway","value":100,"code":"NO"},
{"name":"Oman","value":93.4,"code":"OM"},
{"name":"Pakistan","value":91.4,"code":"PK"},
{"name":"Palau","value":null,"code":"PW"},
{"name":"Panama","value":94.7,"code":"PA"},
{"name":"Papua New Guinea","value":40,"code":"PG"},
{"name":"Paraguay","value":98,"code":"PY"},
{"name":"Peru","value":86.7,"code":"PE"},
{"name":"Philippines","value":91.8,"code":"PH"},
{"name":"Poland","value":98.3,"code":"PL"},
{"name":"Por tugal","value":100,"code":"PT"},
{"name":"Qatar","value":100,"code":"QA"},
{"name":"Republic of Korea","value":null,"code":"KR"},
{"name":"Republic of Moldova","value":88.4,"code":"MD"},
{"name":"Romania","value":100,"code":"RO"},
{"name":"Russian Federation","value":96.9,"code":"RU"},
{"name":"Rwanda","value":76.1,"code":"RW"},
{"name":"Saint Kitts and Nevis","value":98.3,"code":"KN"},
{"name":"Saint Lucia","value":96.3,"code":"LC"},
{"name":"Saint Vincent and the Grenadines","value":95.1,"code":"VC"},
{"name":"Samoa","value":99,"code":"WS"},
{"name":"San Marino","value":null,"code":"SM"},
{"name":"Sao Tome and Principe","value":97.1,"code":"ST"},
{"name":"Saudi Arabia","value":97,"code":"SA"},
{"name":"Senegal","value":78.5,"code":"SN"},
{"name":"Serbia","value":99.2,"code":"RS"},
{"name":"Seychelles","value":95.7,"code":"SC"},
{"name":"Sierra Leone","value":62.6,"code":"SL"},
{"name":"Singapore","value":100,"code":"SG"},
{"name":"Slovakia","value":100,"code":"SK"},
{"name":"Slovenia","value":99.5,"code":"SI"},
{"name":"Solomon Islands","value":80.8,"code":"SB"},
{"name":"Somalia","value":null,"code":"SO"},
{"name":"South Africa","value":93.2,"code":"ZA"},
{"name":"South Sudan","value":58.7,"code":"SS"},
{"name":"Spain","value":100,"code":"ES"},
{"name":"Sri Lanka","value":95.6,"code":"LK"},
{"name":"Sudan","value":null,"code":"SD"},
{"name":"Suriname","value":94.8,"code":"SR"},
{"name":"Swaziland","value":74.1,"code":"SZ"},
{"name":"Sweden","value":100,"code":"SE"},
{"name":"Switzerland","value":100,"code":"CH"},
{"name":"Syrian Arab Republic","value":90.1,"code":"SY"},
{"name":"Tajikistan","value":73.8,"code":"TJ"},
{"name":"Thailand","value":97.8,"code":"TH"},
{"name":"The former Yugoslav Republic of","value":99.4,"code":""},
{"name":"Timor-Leste","value":71.9,"code":"TL"},
{"name":"Togo","value":63.1,"code":"TG"},
{"name":"Tonga","value":99.6,"code":"TO"},
{"name":"Trinidad and Tobago","value":95.1,"code":"TT"},
{"name":"Tunisia","value":97.7,"code":"TN"},
{"name":"Turkey","value":100,"code":"TR"},
{"name":"Turkmenistan","value":null,"code":"TM"},
{"name":"Tuvalu","value":97.7,"code":"TV"},
{"name":"Uganda","value":79,"code":"UG"},
{"name":"Ukraine","value":96.2,"code":"UA"},
{"name":"United Arab Emirates","value":99.6,"code":"AE"},
{"name":"United Kingdom","value":100,"code":"GB"},
{"name":"United Republic of Tanzania","value":55.6,"code":"TZ"},
{"name":"United States of America","value":99.2,"code":"US"},
{"name":"Uruguay","value":99.7,"code":"UY"},
{"name":"Uzbekistan","value":null,"code":"UZ"},
{"name":"Vanuatu","value":94.5,"code":"VU"},
{"name":"Venezuela (Bolivarian Republic of)","value":93.1,"code":"VE"},
{"name":"Viet Nam","value":97.6,"code":"VN"},
{"name":"Yemen","value":null,"code":"YE"},
{"name":"Zambia","value":65.4,"code":"ZM"},
{"name":"Zimbabwe","value":76.9,"code":"ZW"}];

        // Add lower case codes to the data set for inclusion in the tooltip.pointFormat
        $.each(data, function () {
            this.flag = this.code.replace('UK', 'GB').toLowerCase();
        });

        // Initiate the chart
        $('#project-one').highcharts('Map', {

            title: {
                text: 'Proportion of the 2015 population that gained access since 1990 (%)'
            },

			credits: {
            	text: 'Zhinan Yin | IDV460',
            	href: 'index.html'
            },

            legend: {
                title: {
                    text: 'Population of Drinking Water Usage percentage (%)',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.textColor) || 'black'
                    }
                }
            },

            mapNavigation: {
                enabled: true,
                buttonOptions: {
                    verticalAlign: 'bottom'
                }
            },

            tooltip: {
                backgroundColor: 'none',
                borderWidth: 0,
                shadow: false,
                useHTML: true,
                padding: 0,
                pointFormat: '<span class="f32"><span class="flag {point.flag}"></span></span>' +
                    ' {point.name}: <b>{point.value}</b>/%',
                positioner: function () {
                    return { x: 0, y: 250 };
                }
            },

            colorAxis: {
                min: 1,
                max: 100,
                minColor: '#C0CECE',
				maxColor: '#135C6D',
                type: 'linear'
            },

            series : [{
                data : data,
                mapData: Highcharts.maps['custom/world-highres3'],
                joinBy: ['iso-a2', 'code'],
                name: 'Population density',
                states: {
                    hover: {
                        color: '#8EE8DF'
                    }
                }
            }]
        });
    //});
});