$(function () {

    //$.getJSON('https://www.highcharts.com/samples/data/jsonp.php?filename=world-population-density.json&callback=?', function (data) {
    
    var data = [{"name":"Afghanistan","value":16.5,"code":"AF"},
{"name":"Albania","value":32.9,"code":"AL"},
{"name":"Algeria","value":26.9,"code":"DZ"},
{"name":"Andorra","value":null,"code":"AD"},
{"name":"Angola","value":16.3,"code":"AO"},
{"name":"Antigua and Barbuda","value":30.5,"code":"AG"},
{"name":"Argentina","value":31.1,"code":"AR"},
{"name":"Armenia","value":32.7,"code":"AM"},
{"name":"Australia","value":37.2,"code":"AU"},
{"name":"Austria","value":42.7,"code":"AT"},
{"name":"Azerbaijan","value":29.7,"code":"AZ"},
{"name":"Bahamas","value":31.8,"code":"BS"},
{"name":"Bahrain","value":30.1,"code":"BH"},
{"name":"Bangladesh","value":25.1,"code":"BD"},
{"name":"Barbados","value":36.9,"code":"BB"},
{"name":"Belarus","value":39.3,"code":"BY"},
{"name":"Belgium","value":41.6,"code":"BE"},
{"name":"Belize","value":23,"code":"BZ"},
{"name":"Benin","value":18.4,"code":"BJ"},
{"name":"Bhutan","value":25.8,"code":"BT"},
{"name":"Bolivia (Plurinational State of)","value":22.4,"code":"BO"},
{"name":"Bosnia and Herzegovina","value":39.5,"code":"BA"},
{"name":"Botswana","value":22.5,"code":"BW"},
{"name":"Brazil","value":30.3,"code":"BR"},
{"name":"Brunei Darussalam","value":30.5,"code":"BN"},
{"name":"Bulgaria","value":43,"code":"BG"},
{"name":"Burkina Faso","value":17.1,"code":"BF"},
{"name":"Burundi","value":17.6,"code":"BI"},
{"name":"Cote d'Ivoire","value":19,"code":"CI"},
{"name":"Cabo Verde","value":24.2,"code":"CV"},
{"name":"Cambodia","value":24.4,"code":"KH"},
{"name":"Cameroon","value":18.3,"code":"CM"},
{"name":"Canada","value":40.1,"code":"CA"},
{"name":"Central African Republic","value":19.7,"code":"CF"},
{"name":"Chad","value":15.8,"code":"TD"},
{"name":"Chile","value":33.1,"code":"CL"},
{"name":"China","value":37.4,"code":"CN"},
{"name":"Colombia","value":27.7,"code":"CO"},
{"name":"Comoros","value":19.1,"code":"KM"},
{"name":"Congo","value":18.8,"code":"CG"},
{"name":"Cook Islands","value":null,"code":"CK"},
{"name":"Costa Rica","value":29.7,"code":"CR"},
{"name":"Croatia","value":42.6,"code":"HR"},
{"name":"Cuba","value":40.1,"code":"CU"},
{"name":"Cyprus","value":35.2,"code":"CY"},
{"name":"Czech Republic","value":40.3,"code":"CZ"},
{"name":"Democratic People's Republic of Korea","value":33.6,"code":"KP"},
{"name":"Democratic Republic of the Congo","value":17.4,"code":"CD"},
{"name":"Denmark","value":41.1,"code":"DK"},
{"name":"Djibouti","value":22.8,"code":"DJ"},
{"name":"Dominica","value":null,"code":"DM"},
{"name":"Dominican Republic","value":25.8,"code":"DO"},
{"name":"Ecuador","value":26.1,"code":"EC"},
{"name":"Egypt","value":25.2,"code":"EG"},
{"name":"El Salvador","value":24.1,"code":"SV"},
{"name":"Equatorial Guinea","value":20.6,"code":"GQ"},
{"name":"Eritrea","value":18.4,"code":"ER"},
{"name":"Estonia","value":40.9,"code":"EE"},
{"name":"Ethiopia","value":18.2,"code":"ET"},
{"name":"Fiji","value":27.1,"code":"FJ"},
{"name":"Finland","value":42.3,"code":"FI"},
{"name":"France","value":40.6,"code":"FR"},
{"name":"Gabon","value":20.7,"code":"GA"},
{"name":"Gambia","value":17,"code":"GM"},
{"name":"Georgia","value":37.6,"code":"GE"},
{"name":"Germany","value":45.5,"code":"DE"},
{"name":"Ghana","value":20.6,"code":"GH"},
{"name":"Greece","value":42.8,"code":"GR"},
{"name":"Grenada","value":26.3,"code":"GD"},
{"name":"Guatemala","value":19.4,"code":"GT"},
{"name":"Guinea","value":18.6,"code":"GN"},
{"name":"Guinea-Bissau","value":19.1,"code":"GW"},
{"name":"Guyana","value":22.6,"code":"GY"},
{"name":"Haiti","value":22.2,"code":"HT"},
{"name":"Honduras","value":21.9,"code":"HN"},
{"name":"Hungary","value":40.6,"code":"HU"},
{"name":"Iceland","value":35.5,"code":"IS"},
{"name":"India","value":26.4,"code":"IN"},
{"name":"Indonesia","value":27.8,"code":"ID"},
{"name":"Iran (Islamic Republic of)","value":28.5,"code":"IR"},
{"name":"Iraq","value":19.7,"code":"IQ"},
{"name":"Ireland","value":35.3,"code":"IE"},
{"name":"Israel","value":30.1,"code":"IL"},
{"name":"Italy","value":44.3,"code":"IT"},
{"name":"Jamaica","value":27.7,"code":"JM"},
{"name":"Japan","value":45.9,"code":"JP"},
{"name":"Jordan","value":23.4,"code":"JO"},
{"name":"Kazakhstan","value":29.4,"code":"KZ"},
{"name":"Kenya","value":18.8,"code":"KE"},
{"name":"Kiribati","value":23.5,"code":"KI"},
{"name":"Kuwait","value":29.2,"code":"KW"},
{"name":"Kyrgyzstan","value":24.6,"code":"KG"},
{"name":"Lao People's Democratic Republic","value":21.4,"code":"LA"},
{"name":"Latvia","value":41.5,"code":"LV"},
{"name":"Lebanon","value":29.8,"code":"LB"},
{"name":"Lesotho","value":20.7,"code":"LS"},
{"name":"Liberia","value":18.5,"code":"LR"},
{"name":"Libya","value":26.6,"code":"LY"},
{"name":"Lithuania","value":39.3,"code":"LT"},
{"name":"Luxembourg","value":39,"code":"LU"},
{"name":"Madagascar","value":18.4,"code":"MG"},
{"name":"Malawi","value":17.2,"code":"MW"},
{"name":"Malaysia","value":27.4,"code":"MY"},
{"name":"Maldives","value":25,"code":"MV"},
{"name":"Mali","value":16.3,"code":"ML"},
{"name":"Malta","value":40.9,"code":"MT"},
{"name":"Marshall Islands","value":null,"code":"MH"},
{"name":"Mauritania","value":19.8,"code":"MR"},
{"name":"Mauritius","value":34.6,"code":"MU"},
{"name":"Mexico","value":27,"code":"MX"},
{"name":"Micronesia (Federated States of)","value":21,"code":"FM"},
{"name":"Monaco","value":null,"code":"MC"},
{"name":"Mongolia","value":26.8,"code":"MN"},
{"name":"Montenegro","value":37.1,"code":"ME"},
{"name":"Morocco","value":27,"code":"MA"},
{"name":"Mozambique","value":17.3,"code":"MZ"},
{"name":"Myanmar","value":29,"code":"MM"},
{"name":"Namibia","value":21.2,"code":"NA"},
{"name":"Nauru","value":null,"code":"NR"},
{"name":"Nepal","value":22.4,"code":"NP"},
{"name":"Netherlands","value":41.8,"code":"NL"},
{"name":"New Zealand","value":37,"code":"NZ"},
{"name":"Nicaragua","value":23.1,"code":"NI"},
{"name":"Niger","value":15,"code":"NE"},
{"name":"Nigeria","value":17.8,"code":"NG"},
{"name":"Niue","value":null,"code":"NU"},
{"name":"Norway","value":39,"code":"NO"},
{"name":"Oman","value":26.3,"code":"OM"},
{"name":"Pakistan","value":22.5,"code":"PK"},
{"name":"Palau","value":null,"code":"PW"},
{"name":"Panama","value":27.9,"code":"PA"},
{"name":"Papua New Guinea","value":20.9,"code":"PG"},
{"name":"Paraguay","value":23.9,"code":"PY"},
{"name":"Peru","value":26.5,"code":"PE"},
{"name":"Philippines","value":23,"code":"PH"},
{"name":"Poland","value":38.8,"code":"PL"},
{"name":"Portugal","value":42.2,"code":"PT"},
{"name":"Qatar","value":31.7,"code":"QA"},
{"name":"Republic of Korea","value":39.4,"code":"KR"},
{"name":"Republic of Moldova","value":35.8,"code":"MD"},
{"name":"Romania","value":39.4,"code":"RO"},
{"name":"Russian Federation","value":38.3,"code":"RU"},
{"name":"Rwanda","value":18.2,"code":"RW"},
{"name":"Saint Kitts and Nevis","value":null,"code":"KN"},
{"name":"Saint Lucia","value":30.5,"code":"LC"},
{"name":"Saint Vincent and the Grenadines","value":29,"code":"VC"},
{"name":"Samoa","value":21,"code":"WS"},
{"name":"San Marino","value":null,"code":"SM"},
{"name":"Sao Tome and Principe","value":19.2,"code":"ST"},
{"name":"Saudi Arabia","value":27.5,"code":"SA"},
{"name":"Senegal","value":18.1,"code":"SN"},
{"name":"Serbia","value":38.7,"code":"RS"},
{"name":"Seychelles","value":32.6,"code":"SC"},
{"name":"Sierra Leone","value":19.1,"code":"SL"},
{"name":"Singapore","value":38.1,"code":"SG"},
{"name":"Slovakia","value":38.2,"code":"SK"},
{"name":"Slovenia","value":42.4,"code":"SI"},
{"name":"Solomon Islands","value":19.7,"code":"SB"},
{"name":"Somalia","value":16.3,"code":"SO"},
{"name":"South Africa","value":26,"code":"ZA"},
{"name":"South Sudan","value":18.6,"code":"SS"},
{"name":"Spain","value":41.4,"code":"ES"},
{"name":"Sri Lanka","value":31.4,"code":"LK"},
{"name":"Sudan","value":19.2,"code":"SD"},
{"name":"Suriname","value":28.5,"code":"SR"},
{"name":"Swaziland","value":20.1,"code":"SZ"},
{"name":"Sweden","value":41,"code":"SE"},
{"name":"Switzerland","value":42,"code":"CH"},
{"name":"Syrian Arab Republic","value":22.4,"code":"SY"},
{"name":"Tajikistan","value":21.7,"code":"TJ"},
{"name":"Thailand","value":36.9,"code":"TH"},
{"name":"The former Yugoslav republic of Macedonia","value":37.1,"code":"MK"},
{"name":"Timor-Leste","value":16.6,"code":"TL"},
{"name":"Togo","value":18.9,"code":"TG"},
{"name":"Tonga","value":21.3,"code":"TO"},
{"name":"Trinidad and Tobago","value":33.3,"code":"TT"},
{"name":"Tunisia","value":30.3,"code":"TN"},
{"name":"Turkey","value":29.4,"code":"TR"},
{"name":"Turkmenistan","value":25.6,"code":"TM"},
{"name":"Tuvalu","value":null,"code":"TV"},
{"name":"Uganda","value":15.8,"code":"UG"},
{"name":"Ukraine","value":39.7,"code":"UA"},
{"name":"United Arab Emirates","value":30,"code":"AE"},
{"name":"United Kingdom of Great Britain and Northern Ireland","value":40.2,"code":"GB"},
{"name":"United Republic of Tanzania","value":17.5,"code":"TZ"},
{"name":"United States of America","value":37.4,"code":"US"},
{"name":"Uruguay","value":34.4,"code":"UY"},
{"name":"Uzbekistan","value":25.3,"code":"UZ"},
{"name":"Vanuatu","value":21.7,"code":"VU"},
{"name":"Venezuela (Bolivarian Republic of)","value":27,"code":"VE"},
{"name":"Viet Nam","value":29.8,"code":"VN"},
{"name":"Yemen","value":19.1,"code":"YE"},
{"name":"Zambia","value":16.6,"code":"ZM"},
{"name":"Zimbabwe","value":19.5,"code":"ZW"}];

        // Initiate the chart
        $('#worldmap').highcharts('Map', {

            title : {
                text : 'Zoom in on country by double click'
            },
            
            credits: {
            	text: 'Zhinan Yin | IDV460',
            	href: 'index.html'
            },
            
            chart: {
            	style: {
            		fontfamily: 'Cinzel',
            		backgroundColor: 'rgba(255,255,255,0)'
            	}
            },

            mapNavigation: {
                enabled: true,
                enableDoubleClickZoomTo: true
            },

            colorAxis: {
           	    minColor: '#F9CC67',
				maxColor: '#592E11',
                min: 10,
                max: 50,
                type: 'linear'
            },

            series : [{
                data : data,
                mapData: Highcharts.maps['custom/world-highres'],
                joinBy: ['iso-a2', 'code'],
                name: 'Median age',
                states: {
                    hover: {
                        color: '#63662E'
                    }
                },
                
            dataLabels: {
            	enabled: true,
            	color: 'white',
            	style: {
            		fontSize: '6px',
            		textShadow: 'none',
            		textTransform: 'uppercase'
            	},
            	format: '{point.name}'
            },
            
                tooltip: {
                    valueSuffix: 'years'
                }
            }]
        });
    //});
});